CLASSES1 = ['1', '2', '3', '3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '4', '4.1', '4.2', '5', '5.1', '6', '7', '8', '9', '10', '10.1', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '37.1', '38', '39','40','41','42','43','44']
CLASSES2 = ["Cystoid macular edema",
"Diffuse macular edema", 
"Diabetic macular edema",
"Hemangioma capillanisum",
"Filling defect",
"Retinal neovascularization",
"Laser spot",
"Blood spots in retina",
"Microvascular anomaly",
"Preretinal hemorrhage",
"Vein occlusion in Uveal inflammatory", 
"Central retinal vein occlusion", 
"Branch retinal vein occlusion", 
"Macular edema in Uveal inflammatory", 
"Uveitis",
"Epiretinal membranes",
"Semisolid drusen",
"Familial semisolid drusen",
"Age-related macular degeneration",
"Choroid neovascularization",
"Fibrovascular scarring in the macula.....",
"Occult macular area choroidal neovascularization",
"Angioid streaks choroidal neovascularization",
"Angioid streaks",
"Choroidal neovascularization in high myopia",
"Polypoidal choroidal vasculopathy",
"Branching vascular network",
"Macular hemorrhages",
"Macular hemorrhages in high myopia",
"Lacquer crack in macular region",
"Atrophic maculopathy with pathologic myopia",
"Scar in macular area",
"Pigment epithelial detachment",
"Serous pigment epithelial detachment",
"Neuroepithelial detachment in macular area",
"Central serous chorioretinopathy",
"Macular ischemia",
"Macular coloboma",
"Macular dystrophy",
"Macular hole",
"Pseudo Macular hole",
"Vitelloid macular degeneration",
"Stargardt disease",
"Macular Telangiectasia",
"Congenital macular retinoschisis",
"Capillary occlusion",
"leakage points",
"retinal pigment epithelium lesion macular oedema",
"osteoblast-like cells",
"Choroid laceration",
"retinal periphlebitis macular oedema",
"Focal atrophy",
"macular atrophy",
"Retinal aneurysmal dilation",
"Peripheral Retinal Degeneration",
"Vitreous floaters"
]
